# 嵌入向量维度
embedding_size: 64
# 特征嵌入维度
feat_embed_dim: 64
# 权重大小
weight_size: [64, 64]

# 学习率调度器参数 [衰减率, 步长]
learning_rate_scheduler: [0.96, 50]
# 融合系数
lambda_coeff: 0.9
# 正则化权重
# reg_weight: [0.0, 1e-05, 1e-04, 1e-03]
reg_weight: [1e-05]

# 协同过滤模型
cf_model: lightgcn
# Dropout率
mess_dropout: [0.1, 0.1]
# 图神经网络层数
n_layers: 1
# KNN的K值
knn_k: 10

# 学习率
# learning_rate: [0.0001, 0.0005, 0.001, 0.005]
learning_rate: [0.001]

# 超参数列表
hyper_parameters: ["reg_weight", "learning_rate"]